Intro_foro/Intro_foro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('poll', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('vote/<poll_id>/', views.vote, name='vote'),
    path('results/<poll_id>/', views.results, name='results'),
    path('', include('apps.network.urls', namespace ='network')),
    path('', include('apps.users.urls', namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intro_foro/apps/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
]

Intro_foro/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('create-post/', views.create_post, name='create-post'),
    path('edit-post/<str:pk>/', views.edit_post, name='edit-post'),
    path('delete-post/<str:pk>/', views.delete_post, name="delete-post"),
    path('like-post/<str:pk>/', views.like_post, name='like-post'),
    path('post-detail/<int:pk>/', views.post_detail, name='post-detail'),
]

Intro_foro/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import uuid
from django.utils import timezone
from django.conf import settings

class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts', null=True)
    image = models.ImageField(null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    quote = models.TextField(null=True, blank=True)
    link = models.URLField(null=True, blank=True)
    
    def __str__(self):
        return self.quote

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments', null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', null=True)
    text = models.TextField()

Intro_foro/posts/forms.py
from .models import Post, Comment
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('quote', 'image', 'link')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].label = 'Imagen'
        self.fields['quote'].label = ''  
        self.fields['image'].required = False
        self.fields['quote'].widget.attrs.update({'class': 'form-control'})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

Intro_foro/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponseRedirect

@login_required

def like_post(request, pk):
    post = Post.objects.get(pk=pk)
    
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def posts(request):
    posts = Post.objects.all().order_by('-created_at')
    liked_posts = Post.objects.filter(likes=request.user)
    post_comments = {}
    for post in posts:
        comments = Comment.objects.filter(post=post)
        post_comments[post.id] = comments

    post_comments_count = {}
    for post in posts:
        post_comments_count[post.id] = post.comments.count()

    return render(request, 'posts/posts.html', {'posts': posts, 'post_comments_count': post_comments_count})

@login_required
def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user  
            post.save()
            return redirect('posts:posts')


    return render(request, 'posts/create_post.html', {'form': form})


def edit_post(request, pk):
    post = Post.objects.get(id=pk)
    form = PostForm(instance=post)

    if post.author != request.user:
        raise Http404("No tienes permiso para editar este post")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()
            return redirect("posts:posts")

    return render(request, 'posts/create_post.html', {'form': form})


def delete_post(request, pk):
    post = Post.objects.get(id=pk)

    if post.author != request.user:
        raise Http404("No tienes permiso para eliminar este post")

    if request.method == "POST":
        post.delete()
        return redirect("posts:posts")

    return render(request, 'posts/delete_post.html', {'post': post})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('posts:post-detail', pk=pk)  

    else:
        comment_form = CommentForm()

    return render(request, 'posts/post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})

Intro_foro/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h3 class="card-title">Crear Nuevo Post</h3>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Agregar Comentario:</p>
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary mt-3">Publicar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Intro_foro/posts/templates/posts/delete_post.html
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}

<div class="profile-form-container">
    <h5 class="card-title">¿Quieres eliminar el post?</h5>
    <p class="card-text">Se eliminará el post permanentemente.</p>
    <form method="POST" action="{% url 'posts:delete-post' post.pk %}">
        {% csrf_token %}
        <a class="btn btn-primary" href="{% url 'posts:posts' %}">Mantener post</a>
        <button type="submit" class="btn btn-primary mt-2">Eliminar post</button>
    </form>
</div>

{% endblock %}

Intro_foro/posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Detalles del Post</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f4f4f4;
            margin: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        h1 {
            font-size: 28px;
            margin-bottom: 10px;
        }
        p {
            font-size: 16px;
            color: #666;
        }
        ul {
            list-style: none;
            padding-left: 0;
        }
        li {
            margin-bottom: 10px;
            padding: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        .comment-form {
            margin-top: 20px;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #fff;
        }
        .comment-form textarea {
            width: 100%;
            height: 100px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            resize: vertical;
        }
        .comment-form button {
            padding: 8px 16px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .comment-form button:hover {
            background-color: #0056b3;
        }
        .back-to-posts {
            display: inline-block;
            padding: 8px 16px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }

        .back-to-posts:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="{% url 'posts:posts' %}" class="back-to-posts">Volver a posts</a>
        <h1>{{ post.quote }}</h1>
        <p>Autor: {{ post.author }}</p>
        <p>Fecha de publicación: {{ post.created_at }}</p>
        
        <!-- Muestra los comentarios del post -->
        <h2>Comentarios:</h2>
        <ul>
            {% for comment in comments %}
            <li>
                <strong>{{ comment.author }}</strong>: {{ comment.text }}
            </li>
            {% endfor %}
        </ul>

        <!-- Formulario para agregar comentarios -->
        <div class="comment-form">
            <h2>Agregar Comentario:</h2>
            <form method="post" action="{% url 'posts:post-detail' post.pk %}">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit">Enviar comentario</button>
            </form>
        </div>
    </div>
</body>
</html>

Intro_foro/posts/templates/posts/posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
    {% include 'navbar.html' %}
{% else %}
    {% include 'user/login.html' %}
    {% include 'base1.html' %}
{% endif %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
    .small-profile-pic {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        margin-right: 2px;
    }
</style>
<div class="post-container">
    {% for post in posts %}
        <div class="post">
            <div class="post-header d-flex justify-content-between">
                <div class="d-flex">
                    <a href={{ post.author.get_absolute_url }}>
                        <img class="small-profile-pic" src="{{ post.author.profile_pic.url }}" alt="{{ post.author.username }} profile picture">
</a>
                    <h6 class="post-user">{{post.author}}</h6>
                </div>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'posts:edit-post' post.pk %}">Editar</a>
                              <a class="dropdown-item" href="{% url 'posts:delete-post' post.pk %}">Eliminar</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="post-pic-container">
                {% if post.image %}
                    <img class="post-pic" src="{{post.image.url}}">
                {% else %}
                {% endif %}
                {% if post.link %}
                    <a href="{{ post.link }}">{{ post.link }}</a>
                {% endif %}
            </div>
            <div class="post-footer">
                <div class="likes d-flex">
                    <form action="{% url 'posts:like-post' post.pk %}" method="post">
                        {% csrf_token %}
                        <a href="{% url 'posts:like-post' post.pk %}" class="like-btn">
                            {% if post in liked_posts %}
                                <i class="fas fa-heart" style="color: red; margin-right: 5px;"></i>
                            {% else %}
                                <i class="far fa-heart" style="color: black; margin-right: 5px;"></i>
                            {% endif %}
                        </a>
                    </form>
<p style="margin-left: 5px;"><strong>{{ post.likes.count }} likes</strong></p>
                </div>
                <p class="quote"><strong>{{ post.author }}</strong> {{ post.quote }}</p>
                <a href="{% url 'posts:post-detail' post.pk %}#comments-section">
                    <p class="text-muted">Ver los {{ post.comments.all.count }} comentarios</p>
                </a>
                <small class="text-muted">{{ post.created_at|date:"M d, Y" }}</small>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}