Intro_foro/Intro_foro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('poll', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('vote/<poll_id>/', views.vote, name='vote'),
    path('results/<poll_id>/', views.results, name='results'),
    path('', include('apps.network.urls', namespace ='network')),
    path('', include('apps.users.urls', namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intro_foro/apps/users/urls.py
from django.urls import path
from .views import change_profile_picture
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('change_profile_picture/', change_profile_picture, name='change_profile_picture'),
]

Intro_foro/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('create-post/', views.create_post, name='create-post'),
    path('edit-post/<str:pk>/', views.edit_post, name='edit-post'),
    path('delete-post/<str:pk>/', views.delete_post, name="delete-post"),
    path('like-post/<str:pk>/', views.like_post, name='like-post'),
    path('post-detail/<int:pk>/', views.post_detail, name='post-detail'),
]

Intro_foro/apps/users/models.py
import random
import string

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from apps.network.models import Post


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class CustomAccountManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,
                          last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **other_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    profile_pic = models.ImageField(upload_to='users/', default='users/default.png')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    profile_pic = models.ImageField(
        upload_to='users/', default='users/default.png')
    bio = models.TextField(_(
        'Bio'), max_length=500, blank=True)
    followers = models.ManyToManyField(
        "self",
        related_name='following',
        symmetrical=False,
        blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    register_date = models.DateTimeField(default=timezone.now)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.slug])

    def count_following(self):
        users_following = UserProfile.objects.filter(followers=self)
        print(users_following)
        return users_following.count()

    def count_posts(self):
        return Post.objects.filter(author=self).count()

    def is_follower(self, other_user):
        if UserProfile.objects.filter(followers=other_user):
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + self.email)
        super(UserProfile, self).save(*args, **kwargs)

Intro_foro/users/models.py
import random
import string

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from posts.models import Post


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class CustomAccountManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name,
                          last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **other_fields)


class UserProfile(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    profile_pic = models.ImageField(
        upload_to='users/', default='users/default.png')
    bio = models.TextField(_(
        'Bio'), max_length=500, blank=True)
    followers = models.ManyToManyField(
        "self",
        related_name='following',
        symmetrical=False,
        blank=True)
    slug = models.SlugField(max_length=255, unique=True)

    register_date = models.DateTimeField(default=timezone.now)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('users:user_detail', args=[self.slug])

    def count_following(self):
        users_following = UserProfile.objects.filter(followers=self)
        print(users_following)
        return users_following.count()

    def count_posts(self):
        return Post.objects.filter(author=self).count()

    def is_follower(self, other_user):
        if UserProfile.objects.filter(followers=other_user):
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + self.email)
        super(UserProfile, self).save(*args, **kwargs)

Intro_foro/apps/users/forms.py
from django import forms
from .models import UserProfile


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'loginEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'id': 'loginPassword',
            'type': 'password',
            'class': 'form-control',
        })
    )


class UserSignUpForm(forms.Form):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'id': 'signupEmail',
                'type': 'email',
                'class': 'form-control'
            }
        )
    )

    first_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))

    last_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control'
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'signupPassword',
                'type': 'password',
                'class': 'form-control'
            }
        ))

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
                'class': 'form-control'
            }
        ))

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Las Contraseñas no coinciden')
        return cd['password2']

class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']
        widgets = {
            'profile_pic': forms.FileInput(attrs={'accept': 'image/*'}),
        }

Intro_foro/apps/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .forms import UserProfileUpdateForm
from .forms import UserLoginForm, UserSignUpForm


def login_view(request):
    login_form = UserLoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Has iniciado sesion correctamente')
            return redirect('/posts')
        else:
            messages.warning(
                request, 'Correo Electronico o Contrasena invalida')
            return redirect('network:casa')

    messages.error(request, 'Formulario Invalido')
    return redirect('network:casa')


def signup_view(request):
    signup_form = UserSignUpForm(request.POST or None)
    if signup_form.is_valid():
        email = signup_form.cleaned_data.get('email')
        first_name = signup_form.cleaned_data.get('first_name')
        last_name = signup_form.cleaned_data.get('last_name')
        password = signup_form.cleaned_data.get('password')
        try:
            user = get_user_model().objects.create(
                email=email,
                first_name=first_name,
                last_name=last_name,
                password=make_password(password),
                is_active=True
            )
            login(request, user)
            return redirect('users:profile')
        except Exception as e:
            print(e)
            return JsonResponse({'detail': f'{e}'})


    return render(request, 'user/login.html', {'signup_form': signup_form})


def logout_view(request):
    logout(request)
    return redirect('network:casa')


@login_required(login_url='network:casa')
def profile_view(request):
    return render(request, 'user/profile.html')


def user_detail(request, slug):
    user = get_object_or_404(get_user_model(), slug=slug)
    is_follower = False
    try:
        if user.is_follower(request.user):
            is_follower = True
    except:
        messages.warning(
            request, 'Debes Iniciar sesion para mas funcionalidades')

    return render(request, 'user/user_detail.html', {'user_detail': user, "is_follower": is_follower})


@login_required(login_url='network:casa')
def follow(request, slug):
    to_follow = get_object_or_404(get_user_model(), slug=slug)
    if to_follow.is_follower(request.user):
        to_follow.followers.remove(request.user)
    else:
        to_follow.followers.add(request.user)
    to_follow.save
    return redirect(to_follow)

def change_profile_picture(request):
    if request.method == 'POST':
        profile_form = UserProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            # Mensaje de éxito y redireccionamiento
            return redirect('users:profile')
    else:
        profile_form = UserProfileUpdateForm(instance=request.user)

    return render(request, 'user/change_profile_picture.html', {'profile_form': profile_form})

Intro_foro/templates/user/change_profile_picture.html
{% extends 'base1.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2 class="text-center">Cambiar Foto de Perfil</h2>
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_profile_pic" class="font-weight-bold">Selecciona una nueva foto de perfil:</label>
              <div class="custom-file">
                <input type="file" name="profile_pic" id="id_profile_pic" class="custom-file-input">
                <label class="custom-file-label" for="id_profile_pic"></label>
              </div>
              {{ profile_form.profile_pic.errors }}
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="btn btn-primary btn-block">Guardar Cambios</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Intro_foro/templates/user/login.html
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
  
          <ul class="nav nav-pills nav-justified mb-3">
            <li class="nav-item">
              <a class="nav-link active show" data-mdb-toggle="pill" href="#navbarLogin-login" role="tab">
                Iniciar Sesion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-mdb-toggle="pill" href="#navbarLogin-signup" role="tab">Registrarse</a>
            </li>
          </ul>
  
          <div class="tab-content" id="tab-content">
            <div class="tab-pane fade show active" id="navbarLogin-login" role="tabpanel">
              <form id="login" class="text-center" action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
  
                <div class="form-outline form-auth-md mb-4">
                  {{ loginForm.email }}
                  <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
                </div>
  
                <div class="form-outline form-auth-md mb-4">
                  {{ loginForm.password }}
                  <label class="form-label" style="margin-left: 0px;">Contraseña</label>
                </div>
  
  
  
                <button type="submit" class="btn btn-primary btn-block mb-4">Iniciar</button>
              </form>
            </div>
  
  
            <div class="tab-pane fade" id="navbarLogin-signup" role="tabpanel">
              <form id="register" class="text-center" action="{% url 'users:signup'%}" method="post">
                {% csrf_token %}
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.email}}
                  <label class="form-label" style="margin-left: 0px;">Correo Electronico</label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.first_name }}
                  <label class="form-label" style="margin-left: 0px;">Nombre</label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.last_name }}
                  <label class="form-label" style="margin-left: 0px;">Apellido</label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.password }}
                  <label class="form-label" style="margin-left: 0px;">Your password
                  </label>
                </div>
  
                <div class="form-outline form-auth-mdb mb-4">
                  {{ signupForm.password2 }}
                  <label class="form-label" style="margin-left: 0px;">Repeat password
                  </label>
  
                </div>
  
                <button class="btn btn-primary btn-block mb-3" type="submit">Registrar</button>
              </form>
  
            </div>
          </div>
  
        </div>
      </div>
    </div>
  </div>
  

Intro_foro/templates/user/profile.html
{% extends "../base1.html" %}

{% block content %}
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user.profile_pic.url }} alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <h4 class="card-title text-center mb-4">{{ user.first_name}} {{ user.last_name}}</h4>
          <div class='row justify-content-center'>
            <p class="col-6 text-center mb-0">Seguidores: <strong>{{ user.followers.all|length }}</strong></p>
            <p class="col-6 text-center mb-0">Seguidos: <strong>{{ user.count_following }}</strong></p>

            <p class="card-text text-center mb-4">{{ user.bio }}</p>
          </div>
          <div class="d-flex flex-column align-items-center">
            <a class='btn btn-danger btn-rounded mb-2' href={% url 'users:logout'%}>
              Cerrar Sesión
            </a>
            <a class='btn btn-danger btn-rounded' href={% url 'users:change_profile_picture'%}>
              Cambiar Foto
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Intro_foro/templates/user/user_detail.html
{% extends "../base1.html" %}

{% block content %}
<div class='container d-flex justify-content-center mt-5 col-md-10 col-xl-8'>
  <div class="card shadow-4-strong mb-3">
    <div class="row g-0">
      <div class="col-md-5">
        <img src={{ user_detail.profile_pic.url }} alt="..." class="img-fluid rounded" />
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class='row justify-content-center'>
            <h4 class="col-12 card-title text-center mb-4">{{ user_detail.first_name}} {{ user_detail.last_name}}</h4>
            <div class='row justify-content-center'>
              <p class="col-6 text-center mb-0">Seguidores: <strong>{{ user.followers.all|length }}</strong></p>
              <p class="col-6 text-center mb-0">Seguidos: <strong>{{ user.count_following }}</strong></p>
  
              <p class="card-text text-center mb-4">{{ user.bio }}</p>


            <p class="card-text text-center mb-5">{{ user_detail.bio }}</p>
            {% if is_follower %}
            <a type="button" class="btn btn-secondary btn-rounded col-5"
              href={% url 'users:follow' slug=user_detail.slug %}>Dejar de Seguir</a>
            {% elif user_detail != user and user.email %}
            <a type="button" id='follow' class="btn btn-primary btn-rounded col-5"
              href={% url 'users:follow' slug=user_detail.slug %}>Seguir</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}