Intro_foro/Intro_foro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('poll', views.home, name='home'),
    path('create/', views.create, name='create'),
    path('vote/<poll_id>/', views.vote, name='vote'),
    path('results/<poll_id>/', views.results, name='results'),
    path('', include('apps.network.urls', namespace ='network')),
    path('', include('apps.users.urls', namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Intro_foro/apps/users/urls.py
from django.urls import path
from .views import change_profile_picture
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('change_profile_picture/', change_profile_picture, name='change_profile_picture'),
]

Intro_foro/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('create-post/', views.create_post, name='create-post'),
    path('edit-post/<str:pk>/', views.edit_post, name='edit-post'),
    path('delete-post/<str:pk>/', views.delete_post, name="delete-post"),
    path('like-post/<str:pk>/', views.like_post, name='like-post'),
    path('post-detail/<int:pk>/', views.post_detail, name='post-detail'),
]

Intro_foro/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://kit.fontawesome.com/1b2de11c6b.js" crossorigin="anonymous"></script>

    <meta charset="utf-8">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
</head>
<body>
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
        {{ message }}
    </div>
    {% endfor %}

    <div id="content">{% block content %} {% endblock %}</div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

Intro_foro/templates/base1.html
<html lang="es">

<head>
  <meta charset="utf-8">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
</head>
{% include 'navbar.html' %}
<body>
    <header>
      {% include "user/login.html" %}           <!-- PROBABLEMENTE DEBA CAMBIAR EL USER POR APPS.USER-->
    </header>


    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role='alert'>
      {{ message }}
    </div>
    {% endfor %}

    <div id="content">{% block content %} {% endblock %}</div>
 
</body>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>

</html>

Intro_foro/templates/home.html
{% extends "./base1.html" %}
{% load static %}
{% block content %}

<div class='container col-lg-8 col-md-12'>
  <div class="text-center">
    <h1 class='my-4'></h1>
    <img src="{% static 'image2.png' %}" alt="" class="img-fluid" />
  </div>

  {% for post in posts %}
  <div class="card mb-3">
    <img src={{post.image.url}} class="card-img-top" />

    <div class="card-body">
      <a href={{ post.author.get_absolute_url }}>
        <h5 class="card-title">{{post.author}}</h5>
      </a>
        <p class="card-text">
            {{post.description}}
        </p>
    </div>

    <div class='card-footer'>
      <p class="card-text">
        <small class="text-muted">{{post.published}}</small>
      </p>
    </div>
  </div>
  {% endfor %}

</div>

{% endblock %}

Intro_foro/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
      <span class="navbar-brand">GreenChats</span>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link" href="/posts">Posts</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'posts:create-post' %}">Nuevo post</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/poll">Desafios</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="/create">Proponer desafio</a>
              </li>
          </ul>
      </div>
      {% endif %}
      <div class="d-flex align-items-center">
          <a href="{% url 'users:profile' %}">
              <img src="{{ user.profile_pic.url }}" class="rounded-circle" height="30" width="30" alt="" loading="lazy" />
          </a>
          {% if user.is_authenticated %}
              <span class="navbar-text ms-2">{{ user.username }}</span>
          {% else %}
              <button type="button" class="btn btn-primary ms-2" data-mdb-toggle="modal" data-mdb-target="#loginModal">Iniciar Sesión</button>
          {% endif %}
      </div>
  </div>
</nav>